<a href="https://colab.research.google.com/github/TasneemBadry/TasneemBadry/blob/main/comp_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data**

the following steps to upload data from kaggle directly

In [ ]:
!pip install --upgrade --force-reinstall --no-deps kaggle
!mkdir ~/.kaggle


     |████████████████████████████████| 58 kB 3.1 MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73051 sha256=0adc7ddc53c078feb48de583a49fedac0dffec017dea251db3d1954cc1899c6b
  Stored in directory: /root/.cache/pip/wheels/62/d6/58/5853130f941e75b2177d281eb7e44b4a98ed46dd155f556dc5
Successfully built kaggle
  Attempting uninstall: kaggle
    Found existing installation: kaggle 1.5.12
    Uninstalling kaggle-1.5.12:
      Successfully uninstalled kaggle-1.5.12


In [ ]:
from google.colab import files
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
# download and process the data from kaggle
!kaggle competitions download -c cisc-873-dm-f22-a2
!unzip "/content/cisc-873-dm-f22-a2.zip" # extracting files
#load data on colab and unzip it

  0% 0.00/1.46M [00:00<?, ?B/s]
100% 1.46M/1.46M [00:00<00:00, 52.3MB/s]
Archive:  /content/cisc-873-dm-f22-a2.zip
  inflating: Speed Dating Data Description.pdf  
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
#now we just start the model
#first step is libraries
import pandas as pd          #pandas help to read data files
import numpy as np           #


In [ ]:
f=pd.read_csv('/content/train.csv') #read data by pandas
f

gender  idg  condtn  wave  round  position  positin1  order  partner  \
0          0    3       2    14     18         2       2.0     14       12   
1          1   14       1     3     10         2       NaN      8        8   
2          1   14       1    13     10         8       8.0     10       10   
3          1   38       2     9     20        18      13.0      6        7   
4          1   24       2    14     20         6       6.0     20       17   
...      ...  ...     ...   ...    ...       ...       ...    ...      ...   
5904       0    1       2     9     20         2       2.0     18        1   
5905       1   24       2     9     20        19      15.0      5        6   
5906       0   13       2    11     21         5       5.0      3       18   
5907       1   10       2     7     16         6      14.0      9       10   
5908       0    7       2    21     22         7       7.0      2       12   

        pid  ...  sinc3_3  intel3_3  fun3_3  amb3_3  attr5_3  sinc5_3  \
0     372.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   
1      63.0  ...      8.0       8.0     7.0     8.0      NaN      NaN   
2     331.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   
3     200.0  ...      9.0       8.0     8.0     6.0      NaN      NaN   
4     357.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   
...     ...  ...      ...       ...     ...     ...      ...      ...   
5904  214.0  ...     12.0      12.0     9.0    12.0      NaN      NaN   
5905  199.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   
5906  290.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   
5907  151.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   
5908  542.0  ...      NaN       NaN     NaN     NaN      NaN      NaN   

      intel5_3  fun5_3  amb5_3    id  
0          NaN     NaN     NaN  2583  
1          NaN     NaN     NaN  6830  
2          NaN     NaN     NaN  4840  
3          NaN     NaN     NaN  5508  
4          NaN     NaN     NaN  4828  
...        ...     ...     ...   ...  
5904       NaN     NaN     NaN  3390  
5905       NaN     NaN     NaN  4130  
5906       NaN     NaN     NaN  1178  
5907       NaN     NaN     NaN  5016  
5908       NaN     NaN     NaN  8149  

[5909 rows x 192 columns]

In [ ]:
f.info(verbose=True)   #to know data types and its numbers of each type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5909 entries, 0 to 5908
Data columns (total 192 columns):
 #    Column    Dtype  
---   ------    -----  
 0    gender    int64  
 1    idg       int64  
 2    condtn    int64  
 3    wave      int64  
 4    round     int64  
 5    position  int64  
 6    positin1  float64
 7    order     int64  
 8    partner   int64  
 9    pid       float64
 10   match     int64  
 11   int_corr  float64
 12   samerace  int64  
 13   age_o     float64
 14   race_o    float64
 15   pf_o_att  float64
 16   pf_o_sin  float64
 17   pf_o_int  float64
 18   pf_o_fun  float64
 19   pf_o_amb  float64
 20   pf_o_sha  float64
 21   attr_o    float64
 22   sinc_o    float64
 23   intel_o   float64
 24   fun_o     float64
 25   amb_o     float64
 26   shar_o    float64
 27   like_o    float64
 28   prob_o    float64
 29   met_o     float64
 30   age       float64
 31   field     object 
 32   field_cd  float64
 33   undergra  object 
 34   mn_sat    object 
 35 

In [ ]:
f.isnull().sum()  #to know each column if contain nanvalues or no and their number in each column

gender         0
idg            0
condtn         0
wave           0
round          0
            ... 
sinc5_3     4496
intel5_3    4496
fun5_3      4496
amb5_3      4496
id             0
Length: 192, dtype: int64

In [ ]:
t=f.drop(columns=['id'])    #drop it because it does not affect in data

In [ ]:
#now we determine inputs (X) and outputs (Y) from columns of data
X=t.iloc[:,t.columns!='match']
Y=t.match

In [ ]:
#and splitting it to train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.33, random_state=42)

# **Full PipLine**

In [ ]:
#Now we need to select each column containing any data type
features_numeric = list(X_train.select_dtypes(include=['float64', 'int64']))  #to select columns which contain data types numeric (float and integer)

features_categorical = list(X_train.select_dtypes(include=['category']))  #to select columns which contain data type text (category)

print('numeric features:', features_numeric)
print('categorical features:', features_categorical)
#printing them to make sure

numeric features: ['gender', 'idg', 'condtn', 'wave', 'round', 'position', 'positin1', 'order', 'partner', 'pid', 'int_corr', 'samerace', 'age_o', 'race_o', 'pf_o_att', 'pf_o_sin', 'pf_o_int', 'pf_o_fun', 'pf_o_amb', 'pf_o_sha', 'attr_o', 'sinc_o', 'intel_o', 'fun_o', 'amb_o', 'shar_o', 'like_o', 'prob_o', 'met_o', 'age', 'field_cd', 'race', 'imprace', 'imprelig', 'goal', 'date', 'go_out', 'career_c', 'sports', 'tvsports', 'exercise', 'dining', 'museums', 'art', 'hiking', 'gaming', 'clubbing', 'reading', 'tv', 'theater', 'movies', 'concerts', 'music', 'shopping', 'yoga', 'exphappy', 'expnum', 'attr1_1', 'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1', 'shar1_1', 'attr4_1', 'sinc4_1', 'intel4_1', 'fun4_1', 'amb4_1', 'shar4_1', 'attr2_1', 'sinc2_1', 'intel2_1', 'fun2_1', 'amb2_1', 'shar2_1', 'attr3_1', 'sinc3_1', 'fun3_1', 'intel3_1', 'amb3_1', 'attr5_1', 'sinc5_1', 'intel5_1', 'fun5_1', 'amb5_1', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar', 'like', 'prob', 'met', 'match_es', 'attr1_s', 'sin

In [ ]:
#let's start preprocessing for data
#we use fullpipline because I can do all steps of preprocessing to all columns in one step to numeric and categorical data
from sklearn.compose import ColumnTransformer   #to transform old data to new data after preprocessing and apply it
from sklearn.datasets import fetch_openml
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer    #kind of imputer to fill nanvalues
from sklearn.preprocessing import StandardScaler, OneHotEncoder   #kind of encoding to convert text data to category to make easier tunning hyperparameters
from sklearn.ensemble import RandomForestClassifier  # in the first try I apply this classifier
from sklearn.model_selection import GridSearchCV   # with grid search

np.random.seed(0)


transformer_numeric = Pipeline(
    steps=[
        ('imputer', SimpleImputer()),   #fill nanvalues to columns contain numeric data
        ('scaler', StandardScaler())]   #and make scalling to data
)
#put this transform in pipline

transformer_categorical = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='constant')),   #fill nanvalues to columns contain text data
        ('onehot', OneHotEncoder(handle_unknown='ignore'))    # and convert it to category by one hot encoding
    ]
)
#put this transform in pipline

#apply this transformers on specified data in features_numeric and features_categorical
preprocessor = ColumnTransformer(
    transformers=[
        ('num', transformer_numeric, features_numeric),
        ('cat', transformer_categorical, features_categorical)
    ]
)


#and put it all steps with the selected classifier to apply them
full_pipline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('my_classifier',
           RandomForestClassifier(),
        )
    ]
)
full_pipline   #just to show it

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['gender', 'idg', 'condtn',
                                                   'wave', 'round', 'position',
                                                   'positin1', 'order',
                                                   'partner', 'pid', 'int_corr',
                                                   'samerace', 'age_o',
                                                   'race_o', 'pf_o_att',
                                                   'pf_o_sin', 'pf_o_int',
                                                   

In [ ]:
#apply full pipline on train data
#and predict it on test data
full_pipline = full_pipline.fit(X_train, y_train)
full_pipline.predict(X_test)

array([0, 0, 0, ..., 1, 0, 1])

# **Grid Search**

In [ ]:
#grid search with this hypapermeter give best accuracy on kaggle but if we change 'my_classifier__max_depth' to 'my_classifier__min_sample_leaf' this give a low accuracy
param_grid = {
    'preprocessor__num__imputer__strategy': ['mean'],
    'my_classifier__n_estimators': [20, 30, 40],
    'my_classifier__max_depth':[10, 20, 30]
}

#we also put pipline (all preprocessing) with tunning
grid_search = GridSearchCV(
    full_pipline, param_grid, cv=2, verbose=1, n_jobs=2,
    scoring='roc_auc')
#and fit grid search on train data
grid_search.fit(X_train, y_train)

print('best score {}'.format(grid_search.best_score_))
print('best score {}'.format(grid_search.best_params_))

Fitting 2 folds for each of 9 candidates, totalling 18 fits
best score 0.8291576400379542
best score {'my_classifier__max_depth': 10, 'my_classifier__n_estimators': 40, 'preprocessor__num__imputer__strategy': 'mean'}


In [ ]:
#read test data
df=pd.read_csv('/content/test.csv')

In [ ]:
#and drop id column from it like I do on train data
d=df.drop(columns=['id'])

In [ ]:
grid_search.predict(d)  #apply tunning grid search on test data

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#and submission the result in kaggle to calculate accuracy score
submission = pd.DataFrame()

submission['id'] = df['id']

submission['match'] = grid_search.predict_proba(d)[:,1]

In [ ]:
submission.to_csv('Grid Search.csv', index=False)   #print submission on excel sheet

Score: 0.86525   
this the first accuracy and the best

In [ ]:
#now we change the type of classifier to logistic regression and apply it on pipline
from sklearn.linear_model import LogisticRegression    #library for logistic classifier

log_pipline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('my_classifier',
           LogisticRegression(solver='liblinear'),
        )
    ]
)
log_pipline     #print it just to make sure

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['gender', 'idg', 'condtn',
                                                   'wave', 'round', 'position',
                                                   'positin1', 'order',
                                                   'partner', 'pid', 'int_corr',
                                                   'samerace', 'age_o',
                                                   'race_o', 'pf_o_att',
                                                   'pf_o_sin', 'pf_o_int',
                                                   

In [ ]:
#apply logistic pipline on train data
#and predict on input test data
log_pipline = log_pipline.fit(X_train, y_train)
log_pipline.predict(X_test)

array([0, 0, 0, ..., 1, 0, 1])

In [ ]:
#now we need to apply new pipline with logistic regression in grid search after change hyperparameters to "my_classifier__penalty"
log_param_grid = {"my_classifier__C":np.logspace(-3,3,7),"my_classifier__penalty":["l1","l2"]}
log_grid_search = GridSearchCV(
    log_pipline, log_param_grid, cv=2, verbose=1, n_jobs=2,
    scoring='roc_auc')
#fit grid search with logistic on train data
log_grid_search.fit(X_train, y_train)

print('best score {}'.format(log_grid_search.best_score_))
print('best score {}'.format(log_grid_search.best_params_))

Fitting 2 folds for each of 14 candidates, totalling 28 fits
best score 0.8576768821260037
best score {'my_classifier__C': 0.1, 'my_classifier__penalty': 'l1'}


In [ ]:
#predict this on test data
log_grid_search.predict(d)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
submission = pd.DataFrame()

submission['id'] = df['id']

submission['match'] = log_grid_search.predict_proba(d)[:,1]

submission.to_csv('Grid Search logistic.csv', index=False)
#this submission is the same best accuracy on kaggle so grid search with any classifier is the best

Score: 0.86525 logistic  
the second best accuracy


# **Random Search**

In [ ]:
#let's start random search with random forest classifier
from sklearn.ensemble import RandomForestRegressor     #for random classifier
from sklearn.model_selection import RandomizedSearchCV      #for random search
random_search = RandomizedSearchCV(
    full_pipline, param_grid, cv=5, verbose=1, n_jobs=2,
    n_iter=10,
    scoring='roc_auc')
random_search.fit(X_train, y_train)
print('best score {}'.format(random_search.best_score_))
print('best score {}'.format(random_search.best_params_))

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:296: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  UserWarning,


Fitting 5 folds for each of 9 candidates, totalling 45 fits
best score 0.8409134516890576
best score {'preprocessor__num__imputer__strategy': 'mean', 'my_classifier__n_estimators': 40, 'my_classifier__max_depth': 10}


In [ ]:
#and predict it on test data
random_search.predict(d)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#submit its result on kaggle to calculate accuracy
submission = pd.DataFrame()

submission['id'] = df['id']

submission['match'] = random_search.predict_proba(d)[:,1]

In [ ]:
submission.to_csv('Random Search.csv', index=False)

Score: 0.85110  
third accuracy, it is not better than grid search

In [ ]:
#random search with logistic regression classifier
log_param_grid = {"my_classifier__C":np.logspace(-3,3,7),"my_classifier__penalty":["l1","l2"]}
log_random_search = RandomizedSearchCV(
    log_pipline, log_param_grid, cv=2, verbose=1, n_jobs=2,
    scoring='roc_auc')

log_random_search.fit(X_train, y_train)

print('best score {}'.format(log_random_search.best_score_))
print('best score {}'.format(log_random_search.best_params_))

Fitting 2 folds for each of 10 candidates, totalling 20 fits
best score 0.8576841214649435
best score {'my_classifier__penalty': 'l1', 'my_classifier__C': 0.1}


In [ ]:
#and predict on test data
log_random_search.predict(d)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#submit on kaggle to give accuracy
submission = pd.DataFrame()

submission['id'] = df['id']

submission['match'] = log_random_search.predict_proba(d)[:,1]

submission.to_csv('Random Search logistic.csv', index=False)
#accuracy of random search with logistic regression is better than accuracy of random search with random forest classifier little bit

Score: 0.85471  
forth result


# **Bayesian Search**

In [ ]:
!pip install scikit-optimize  #install optimizer to apply bayesian search

     |████████████████████████████████| 100 kB 3.8 MB/s 


In [ ]:
#let's start baysian search
#first trial bayes search with SVM
from skopt import BayesSearchCV    #to import bayes search
from skopt.space import Real, Categorical, Integer   #libraries tune hyperparameter of svm
from sklearn.svm import SVC   #import svm


SVC_pipline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('my_svc', SVC(class_weight='balanced',probability=True))
    ]
)


bayes_search = BayesSearchCV(
    SVC_pipline,
    {
        'my_svc__C': Real(1e-6, 1e+6, prior='log-uniform'),
        'my_svc__gamma': Real(1e-6, 1e+1, prior='log-uniform'),
        'my_svc__degree': Integer(1,8),
        'my_svc__kernel': Categorical(['linear', 'poly', 'rbf']),
    },
    n_iter=3,
    random_state=0,
    verbose=1,
    cv=7,
)
#apply bayes search with svm classifier on train data
bayes_search.fit(X_train, y_train)

print('best score {}'.format(bayes_search.best_score_))
print('best score {}'.format(bayes_search.best_params_))
#printing best accuracy for this fitting

Fitting 7 folds for each of 1 candidates, totalling 7 fits
Fitting 7 folds for each of 1 candidates, totalling 7 fits
Fitting 7 folds for each of 1 candidates, totalling 7 fits
best score 0.8188976694527212
best score OrderedDict([('my_svc__C', 0.0012602593949011189), ('my_svc__degree', 8), ('my_svc__gamma', 2.285959941576884), ('my_svc__kernel', 'poly')])


In [ ]:
#and apply it (predict) on test data
bayes_search.predict(d)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#make submission to upload it on kaggle
submission = pd.DataFrame()

submission['id'] = df['id']

submission['match'] = bayes_search.predict_proba(d)[:,1]

In [ ]:
submission.to_csv('Bayes Search.csv', index=False)

Score: 0.70310  
fifth accuracy and this is the least accuracy the model calculate


In [ ]:
#the last try to model
#bayesian search with logistic regression
log_bayes_search = BayesSearchCV(
    log_pipline, log_param_grid,
    n_iter=3,
    random_state=0,
    verbose=1,
    cv=7,
)
#fit bayes search with logistic on train data
log_bayes_search.fit(X_train, y_train)

print('best score {}'.format(log_bayes_search.best_score_))
print('best score {}'.format(log_bayes_search.best_params_))
#printing best accuracy for this fitting

Fitting 7 folds for each of 1 candidates, totalling 7 fits
Fitting 7 folds for each of 1 candidates, totalling 7 fits
Fitting 7 folds for each of 1 candidates, totalling 7 fits
best score 0.8585527109308341
best score OrderedDict([('my_classifier__C', 1.0), ('my_classifier__penalty', 'l1')])


In [ ]:
#and apply it (predict) on test data
log_bayes_search.predict(d)

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#make submission to upload it on kaggle
submission = pd.DataFrame()

submission['id'] = df['id']

submission['match'] = log_bayes_search.predict_proba(d)[:,1]

In [ ]:
submission.to_csv('Bayes Search Logistic.csv', index=False)   #submit it to excel sheet

Score: 0.85775  
sixth and last accuracy for the model

# **Questions**

**A1:**   
Linear Regression is a machine learning algorithm based on supervised regression algorithm. Regression models a target prediction value based on independent variables. It is mostly used for finding out the relationship between variables and forecasting. Different regression models differ based on – the kind of relationship between the dependent and independent variables, they are considering and the number of independent variables being used.  
Logistic regression is basically a supervised classification algorithm. In a classification problem, the target variable(or output), y, can take only discrete values for a given set of features(or inputs), X.



**A2:**  
Decision Tree : Decision tree is the most powerful and popular tool for classification and prediction. A Decision tree is a flowchart like tree structure, where each internal node denotes a test on an attribute, each branch represents an outcome of the test, and each leaf node (terminal node) holds a class label.   
Decision Tree Regression:
Decision tree regression observes features of an object and trains a model in the structure of a tree to predict data in the future to produce meaningful continuous output. Continuous output means that the output/result is not discrete, i.e., it is not represented just by a discrete, known set of numbers or values.  
**Differences:**  


*  Logistics Regression (LR) and Decision Tree (DT) both solve the Classification Problem, and both can be interpreted easily; however, both have pros and cons. Based on the nature of your data choose the appropriate algorithm.
*   Logistic Regression assumes that the data is linearly (or curvy linearly) separable in space, and Decision Trees are non-linear classifiers; they do not require data to be linearly separable.


*  Categorical data works well with Decision Trees, while continuous data work well with Logistic Regression.

If your data is categorical, then Logistic Regression cannot handle pure categorical data (string format). Rather, you need to convert it into numerical data.
*   Decision Trees handle skewed classes nicely if we let it grow fully.

Logistic Regression does not handle skewed classes well. So, in this case, either increase the weight to the minority class or balance the class.  


*   Logistic Regression does not handle missing values; we need to impute those values by mean, mode, and median.

If there are many missing values, then imputing those may not be a good idea, since we are changing the distribution of data by imputing mean everywhere.

Decision Trees works with missing values.
*   Logistic regression will push the decision boundary towards the outlier.

While a Decision Tree, at the initial stage, won't be affected by an outlier, since an impure leaf will contain nine +ve and one –ve outlier. The label for the leaf will be +ve, since the majority are positive.

However, if we let the Decision Tree grow fully, the signal will mote to one side, while the outlier will be moved to the other — there will be one leaf for each outlier.







**A3:**  

1.   Grid search:  
•Try out every combination of the parameters  
•Computationally expensive  
•Global optimal (within the given range)  
•Sklearn: model_selection.GridSearchCV
2.   Random search:  
•Try out a random subset   
•`good enough`  
•Local optimal (within the given range)  
•Efficient (less trials)  
•Sklearn: model_selection.RandomizedSearchCV



**A4:**   
1.   Bayesian Optimization:  
•As an optimization problem  
•Trial -> estimated error -> Bayesian model estimates the next
parameter to try -> trial -> repeat..    
•pip install bayesian-optimization
2.   Random search:  
•Try out a random subset   
•`good enough`  
•Local optimal (within the given range)  
•Efficient (less trials)  
•Sklearn: model_selection.RandomizedSearchCV

**the ideal solutions:**  
grid search with logistic regression or random forest classifiers   
